id: I3486E33B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T09:38:03+00:00'
last_modified: '2022-06-07T21:06:18.259726+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21865
  title: སྙན་ངག་ལ་འཇུག་ཚུལ་ཚིག་རྒྱན་རིག་པའི་སྒོ་འབྱེད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    B115:
      image_group_id: I4989
      title: ''
      total_pages: 670
      order: 1
      base_file: B115.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
