id: P004211
initial_creation_type: ocr
source_metadata:
  id: bdr:W21865
  title: སྙན་ངག་ལ་འཇུག་ཚུལ་ཚིག་རྒྱན་རིག་པའི་སྒོ་འབྱེད
  author: ''
  volumes:
    f6a903a67ed14093aa47e5690dc3e680:
      image_group_id: I4989
      title: ''
      volume_number: 1
      total_pages: 670
